### ISSUE TITLE
only builds static lib under msys/cl

### ISSUE THREAD

**Issue by svigerske** [coin-or-tools/ThirdParty-Glpk#3]
On branch autotools-update, on my setup with msys and MSVC, I only get a static Glpk library build.

From the configure in the glpk subdirectory, I see
```
...
checking whether the /home/stefan/ThirdParty-Glpk-au/compile cl linker (/home/stefan/ThirdParty-Glpk-au/compile cl) supports shared libraries... no
checking dynamic linker characteristics... no
checking how to hardcode library paths into programs... unsupported
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... no
checking whether to build shared libraries... no
checking whether to build static libraries... yes
```

And then a libcoinglpk.a is build:
```
$ ls -la glpk/src/.libs/
total 3.4M
drwxr-xr-x 1 stefan None    0 Jan 10 06:37 ./
drwxr-xr-x 1 stefan None    0 Jan 10 06:37 ../
-rw-r--r-- 1 stefan None 3.2M Jan 10 06:37 libcoinglpk.a
-rw-r--r-- 1 stefan None  891 Jan 10 06:37 libcoinglpk.la
-rw-r--r-- 1 stefan None  892 Jan 10 06:37 libcoinglpk.lai
```

Note that it should actually be `.lib`.
So the build of the OsiGlpk library also says it's not sure what to do with the .a file (sorry for the German, I haven't managed to change that):
```
Microsoft (R) C/C++-Optimierungscompiler Version 19.00.24213.1 f▒r x64
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

cl : Befehlszeile warning D9024 : Unbekannter Typ der Quelldatei "C:/msys64/home/stefan/install-msvc/lib/libcoinglpk.a", Objektdatei wird angenommen.
Microsoft (R) Incremental Linker Version 14.00.24213.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:.libs/OsiGlpk-0.dll
-LIBPATH:C:/msys64/home/stefan/install-msvc/lib
-DLL
-IMPLIB:.libs\OsiGlpk.dll.lib
.libs/OsiGlpkSolverInterface.obj
../Osi/.libs/Osi.dll.lib
C:/msys64/home/stefan/install-msvc/lib/libcoinglpk.a
C:/msys64/home/stefan/install-msvc/lib/CoinUtils.dll.lib
mkl_intel_lp64_dll.lib
mkl_sequential_dll.lib
mkl_core_dll.lib
```
However, it still builds the lib and also the unittest executable can be build and executed.
So maybe that's good enough.

Under mingw (msys+gcc), it actually builds a DLL.

This issue should be considered as assigned to @LouHafer. :)

**Comment by svigerske** [comment]
The static lib seems to be build with `gcc` and there is an `-lm` on the libtool call:
See https://ci.appveyor.com/project/tkralphs/clp-m0kud/build/job/62qdce36flkr8tua#L3088
```
/bin/sh ../libtool  --tag=CC   --mode=link gcc   -version-info 43:0:3 -export-symbols-regex '^glp_*' -no-undefined  -o libcoinglpk.la -rpath /c/projects/dist/lib libcoinglpk_la-amd_1.lo ... libcoinglpk_la-zutil.lo  -lm
```
Eventually, this calls `ar` - instead of `lib`, which is probably the reason why there is an `.a` file create instead of a `.lib`.

Further, the `-lm` is recorded in libcoinglpk.la and linking the CoinUtils dll then fails, see end of
https://ci.appveyor.com/project/tkralphs/clp-m0kud/build/job/62qdce36flkr8tua
```
LINK : fatal error LNK1181: cannot open input file 'm.lib'
```

**Comment by LouHafer** [comment]
I think I've fixed this --- @svigerske, took your suggestion and used the COIN initialisation and build smarts macros instead of trying to pass info from the ThirdParty/Glpk configure.

**Comment by svigerske** [comment]
Seems to work fine for me.

I didn't know about the `-export-symbols-regex` magic in the libtool flags in glpk's makefile. That could be useful for Metis and ASL as well.
